# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimpleX SMP Server
version: "6.5.0-beta.8"
slug: simplex-smp-server
description: Message relay server for SimpleX Chat
url: "https://github.com/ed-asriyan/hassio-simplex/tree/master/simplex-smp-server"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: data
    read_only: false
ports:
  5223/tcp: null
ports_description:
  5223/tcp: SMP server — must be the same value as the 'port' option
options:
  addr: ""
  port: 5223
  pass: ""
  new_queues: true
  restore_messages: true
  expire_messages_days: 21
  expire_ntfs_hours: 24
schema:
  addr: str
  port: int
  pass: str?
  new_queues: bool
  restore_messages: bool
  expire_messages_days: int
  expire_ntfs_hours: int
image: "ghcr.io/ed-asriyan/hassio-simplex-smp-server"
