# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimpleX XFTP Server
version: "6.5.0"
slug: simplex-xftp-server
description: Host a SimpleX XFTP file transfer server on Home Assistant.
url: "https://github.com/ed-asriyan/hassio-simplex"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: data
    read_only: false
ports:
  443/tcp: null
ports_description:
  443/tcp: XFTP server — must be the same value as the 'port' option
options:
  addr: ""
  quota: "10gb"
  port: 443
schema:
  addr: str
  quota: str
  pass: str?
  port: int
image: "ghcr.io/ed-asriyan/hassio-simplex-xftp-server-{arch}"
