# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
FROM simplexchat/xftp-server:v6.5.0

LABEL \
    org.opencontainers.image.title="Home Assistant Add-on: SimpleX XFTP Server" \
    org.opencontainers.image.description="Host a SimpleX XFTP server on Home Assistant." \
    org.opencontainers.image.source="https://github.com/ed-asriyan/hassio-simplex" \
    org.opencontainers.image.licenses="Apache License 2.0"

RUN apt-get update && apt-get install -y --no-install-recommends jq && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
